# Generated by Django 5.1.6 on 2025-02-22 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=20)),
                ('a_email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('shipping_date', models.DateField()),
                ('tax', models.FloatField()),
                ('total_price', models.FloatField()),
                ('status', models.CharField(choices=[('ordr confirm', 'order confirm'), ('order not confirm', 'order not confirm')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='registermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=30, null=True)),
                ('u_email', models.EmailField(max_length=254)),
                ('u_phone', models.BigIntegerField()),
                ('u_password', models.CharField(max_length=8, null=True)),
                ('u_address', models.TextField()),
                ('u_role', models.CharField(max_length=10, null=True)),
                ('u_image', models.ImageField(upload_to='Photos')),
            ],
        ),
        migrations.CreateModel(
            name='delivery_partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_name', models.CharField(max_length=20, null=True)),
                ('delivery_mobile_no', models.BigIntegerField()),
                ('od_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd.order')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='Photos')),
                ('p_name', models.CharField(max_length=20, null=True)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('weight', models.FloatField()),
                ('in_stock', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('ratting', models.IntegerField()),
                ('review_count', models.IntegerField()),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd.category')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd.registermodel')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd.product'),
        ),
        migrations.CreateModel(
            name='payment_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Not Success', 'Not Success')], max_length=20, null=True)),
                ('od_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd.order')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd.registermodel')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd.registermodel'),
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Not Received', 'Not Received')], max_length=20, null=True)),
                ('msg', models.TextField()),
                ('od_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd.order')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd.product')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd.registermodel')),
            ],
        ),
        migrations.CreateModel(
            name='add_to_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('quantity', models.FloatField()),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd.product')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd.registermodel')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField()),
                ('ratting', models.IntegerField()),
                ('review', models.TextField()),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd.product')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd.registermodel')),
            ],
        ),
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(max_length=20)),
                ('sub_datetime', models.DateTimeField()),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd.registermodel')),
            ],
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd.product')),
            ],
        ),
    ]
