# Generated by Django 4.2.13 on 2025-02-24 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='u_id',
            new_name='sellerid',
        ),
    ]
