# Generated by Django 4.2.13 on 2025-02-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dd', '0002_rename_u_id_product_sellerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
