# Generated by Django 4.2.13 on 2025-02-24 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dd', '0003_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ratting',
        ),
        migrations.RemoveField(
            model_name='product',
            name='review_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
