# Generated by Django 4.2.13 on 2025-02-27 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dd', '0004_remove_product_ratting_remove_product_review_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('totalamount', models.FloatField()),
                ('orderstatus', models.IntegerField()),
                ('orderid', models.IntegerField()),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd.product')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd.registermodel')),
            ],
        ),
        migrations.DeleteModel(
            name='add_to_cart',
        ),
    ]
