# Generated by Django 4.2.13 on 2025-02-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dd', '0005_cart_delete_add_to_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_image',
            field=models.ImageField(null=True, upload_to='Photos'),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='u_image',
            field=models.ImageField(null=True, upload_to='Photos'),
        ),
    ]
