# Generated by Django 4.2.13 on 2025-03-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dd', '0006_product_p_image_alter_registermodel_u_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
