# Generated by Django 4.2.13 on 2025-03-25 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dd', '0009_alter_contact_email_alter_contact_msg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finaltotal', models.FloatField()),
                ('phone', models.BigIntegerField()),
                ('address', models.TextField()),
                ('paymode', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd.registermodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='p_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='u_id',
        ),
        migrations.DeleteModel(
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='od_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd.ordermodel'),
        ),
        migrations.AlterField(
            model_name='delivery_partner',
            name='od_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd.ordermodel'),
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
