# Generated by Django 4.2.13 on 2025-03-26 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dd', '0010_ordermodel_remove_order_p_id_remove_order_u_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='userid',
            new_name='u_id',
        ),
    ]
