# Generated by Django 4.2.13 on 2025-03-26 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dd', '0012_ordermodel_p_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='p_id',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='c_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dd.cart'),
        ),
    ]
