# Generated by Django 4.2.13 on 2025-03-26 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dd', '0013_remove_ordermodel_p_id_ordermodel_c_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='p_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dd.product'),
        ),
    ]
