# Generated by Django 4.2.13 on 2025-03-28 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dd', '0014_ordermodel_p_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='date',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='u_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dd.registermodel'),
        ),
    ]
