# Generated by Django 4.2.13 on 2025-03-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dd', '0015_remove_wishlist_date_wishlist_u_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='u_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
