# Generated by Django 4.2.13 on 2025-03-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dd', '0016_alter_registermodel_u_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='u_email',
            field=models.EmailField(max_length=254),
        ),
    ]
