# Generated by Django 4.2.13 on 2025-03-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dd', '0022_alter_registermodel_u_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='u_phone',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
