# Generated by Django 5.0.3 on 2025-04-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dd", "0023_alter_registermodel_u_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="repeat_days",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
