# Generated by Django 4.2.13 on 2026-05-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dd', '0024_ordermodel_repeat_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Review_Photos'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
